CREATE TABLE account1(user_id varchar(20),password varchar(20));
CREATE TABLE account(user_id varchar(20),password varchar(20));

CREATE TABLE station_details(xcod varchar(20),
							 ycod varchar(20) ,
							 station_name  varchar(20), 
							 conn_st_1 varchar(20), 
							 conn_st_2 varchar(20),
							 conn_st_3 varchar(20), 
							 station_type varchar(20));
							 
CREATE TABLE runningdays ( train_no varchar(20), 
							sun INTEGER , 
							mon INTEGER , 
							tue INTEGER, 
							wed INTEGER ,
							thu INTEGER, 
							fri INTEGER, 
							sat INTEGER);

CREATE TABLE train( train_no varchar(20), 
					train_speed varchar(20), 
					train_name varchar(20), 
					train_type varchar(20), 
					source_station varchar(20), 
					dest_station varchar(20), 
					train_route_no varchar(20), 
					priority varchar(20), 
					no_of_stops varchar(20), 
					stopage0 varchar(20), 
					stopage1 varchar(20), 
					stopage2 varchar(20), 
					stopage3 varchar(20), 
					stopage4 varchar(20), 
					stopage5 varchar(20), 
					stopage6 varchar(20), 
					stopage7 varchar(20), 
					stopage8 varchar(20), 
					stopage9 varchar(20), 
					stopage10 varchar(20), 
					stopage11 varchar(20), 
